// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type Session struct {
	Token  string
	Data   []byte
	Expiry float64
}

type User struct {
	ID           int64
	Email        string
	PasswordHash sql.NullString
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type UserProvider struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
}
