// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserProvider(ctx context.Context, arg CreateUserProviderParams) (UserProvider, error)
	GetUserAndProviderInfo(ctx context.Context, arg GetUserAndProviderInfoParams) (GetUserAndProviderInfoRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
